import os
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, LearningRateMonitor
from dataset import ForamsDataModule
from model import HybridForamsModel

def main():
    # 1. Setup DataModule
    # We point to the synthetic data generated by the 2nd-place logic
    data_module = ForamsDataModule(data_dir="data/synthetic", batch_size=4, num_workers=4)

    # 2. Setup Model
    model = HybridForamsModel(
        model_name="facebook/dinov2-base",
        num_classes=14,
        learning_rate=1e-4
    )

    # 3. Setup Callbacks
    checkpoint_callback = ModelCheckpoint(
        dirpath="checkpoints",
        filename="forams-hybrid-{epoch:02d}-{val_loss:.2f}",
        save_top_k=1,
        monitor="val_loss",
        mode="min"
    )
    lr_monitor = LearningRateMonitor(logging_interval='step')

    # 4. Setup Trainer
    trainer = pl.Trainer(
        max_epochs=10,
        accelerator="auto", # automatically use GPU if available
        devices=1,
        precision="16-mixed", # AMP for faster training
        callbacks=[checkpoint_callback, lr_monitor],
        log_every_n_steps=10
    )

    # 5. Train
    # Note: Ensure that the synthetic data has been generated before running this!
    print("Starting training with PyTorch Lightning...")
    trainer.fit(model, datamodule=data_module)

if __name__ == "__main__":
    main()
